---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: service-validate-mail
  name: service-validate-mail
  namespace: <CHANGE YOUR NAMESPACE>
spec:
  replicas: 1
  selector:
    app: service-validate-mail
    deploymentconfig: service-validate-mail
  strategy:
    activeDeadlineSeconds: 21600
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: DevScript
      creationTimestamp: null
      labels:
        app: service-validate-mail
        deploymentconfig: service-validate-mail
    spec:
      containers:
        - env:
            - name: TZ
              value: UTC+3
          ports:
            - containerPort: 5000
              protocol: TCP
          image: >-
            <CHANGE YOR REGISTRY>/<CHANGE YOUR NAMESPACE>/service-validate-mail:1.0.0
          imagePullPolicy: Always
          name: service-validate-mail
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File                     

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: service-validate-mail
  namespace: <CHANGE YOUR NAMESPACE>
spec:
  ports:
  - name: 80-http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    deploymentconfig: service-validate-mail
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: service-validate-mail
  namespace: <CHANGE YOUR NAMESPACE>
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    name: service-validate-mail
  targetCPUUtilizationPercentage: 75
---
apiVersion: v1
kind: Route
metadata:
  name: service-validate-mail
  namespace: <CHANGE YOUR NAMESPACE>
spec:
  host: service-validate-mail-<YOUR DNS ROUTE>
  port:
    targetPort: 80-http
  to:
    kind: Service
    name: service-validate-mail
    weight: 100
  wildcardPolicy: None
